micronaut:
  application:
    name: example-jdbc
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/pets
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: secret
    schema-generate: CREATE_DROP
    dialect: MYSQL
