micronaut:
  application:
    name: example-jdbc
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: 'jdbc:mysql://localhost:3306/pets'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
    schema-generate: CREATE_DROP
    dialect: MYSQL
