micronaut:
  application:
    name: example-jdbc
jackson:
  bean-introspection-module: true
---
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE
